"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, Bell, Building2, BusFront, Calculator, CalendarCheck, Check,
  ChevronRight, CircleGauge, ClipboardList, CloudRain, Construction, Copy, Cpu, Crosshair,
  Database, Download, Fuel, Gauge, IndianRupee, Languages, LayoutDashboard, Map, MapPin,
  Menu, Moon, Navigation, Play, Plus, Presentation, Radio, RotateCcw, Route, Search, Settings,
  ShieldCheck, Smartphone, Sparkles, Sun, TrendingDown, TrendingUp, Truck, UserRound, Waves,
  Wifi, Wrench, X, Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import { Slider } from "@/components/ui/slider";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type HazardType = "Pothole" | "Speed breaker" | "Waterlogging" | "Poor surface";
type Severity = "Critical" | "High" | "Medium";
type Hazard = { id:number; type:HazardType; severity:Severity; road:string; area:string; seen:string; reports:number; confidence:number; x:number; y:number; note:string };
type Vehicle = { id:string; model:string; fleet:string; impacts:number; risk:Severity; health:number; distance:string; efficiency:string; status:string };
type AlertRecord = { id:number; title:string; road:string; vehicle:string; severity:Severity; time:string; status:"Active"|"Acknowledged"|"Resolved"; recommendation:string };
type WorkOrder = { id:string; vehicle:string; task:string; owner:string; due:string; status:"Open"|"In progress"|"Completed"; priority:Severity };

const hazards:Hazard[] = [
  {id:1,type:"Pothole",severity:"Critical",road:"Western Express Highway",area:"Andheri East",seen:"28 sec ago",reports:42,confidence:98,x:30,y:43,note:"Deep impact signature across the left lane. Estimated depth 11–14 cm."},
  {id:2,type:"Speed breaker",severity:"High",road:"LBS Marg",area:"Ghatkopar",seen:"2 min ago",reports:18,confidence:94,x:54,y:56,note:"Unmarked speed breaker after the junction. Approach speed above 34 km/h is unsafe."},
  {id:3,type:"Waterlogging",severity:"Critical",road:"SV Road",area:"Santacruz West",seen:"4 min ago",reports:31,confidence:96,x:41,y:27,note:"Standing water across two lanes. Depth trend is rising after sustained rainfall."},
  {id:4,type:"Poor surface",severity:"Medium",road:"Eastern Express Highway",area:"Vikhroli",seen:"6 min ago",reports:12,confidence:89,x:69,y:38,note:"Uneven patchwork is reducing estimated grip and increasing vibration exposure."},
  {id:5,type:"Pothole",severity:"High",road:"JVLR",area:"Powai",seen:"8 min ago",reports:25,confidence:95,x:63,y:68,note:"Repeated vertical acceleration spike. Hazard occupies the lane centre."},
  {id:6,type:"Speed breaker",severity:"Medium",road:"Link Road",area:"Malad West",seen:"12 min ago",reports:9,confidence:86,x:21,y:69,note:"Low-visibility breaker without paint or advance signage."},
];

const vehicles:Vehicle[] = [
  {id:"MH 02 FR 8421",model:"Tata Nexon EV",fleet:"Mumbai EV Pilot",impacts:418,risk:"Critical",health:58,distance:"1,284 km",efficiency:"6.1 km/kWh",status:"Inspection due"},
  {id:"MH 04 LK 1098",model:"Mahindra XUV400",fleet:"Mumbai EV Pilot",impacts:367,risk:"High",health:67,distance:"1,106 km",efficiency:"6.4 km/kWh",status:"Monitor"},
  {id:"MH 01 TT 6240",model:"Tata Ace EV",fleet:"Last-mile West",impacts:291,risk:"High",health:71,distance:"1,843 km",efficiency:"5.3 km/kWh",status:"Monitor"},
  {id:"MH 03 CP 7712",model:"Mahindra Bolero Neo",fleet:"Field Operations",impacts:184,risk:"Medium",health:82,distance:"938 km",efficiency:"14.2 km/l",status:"Healthy"},
  {id:"MH 12 AX 5509",model:"Tata Tiago EV",fleet:"Mumbai EV Pilot",impacts:142,risk:"Medium",health:88,distance:"764 km",efficiency:"6.7 km/kWh",status:"Healthy"},
];

const startingAlerts:AlertRecord[] = [
  {id:101,title:"Suspension impact threshold exceeded",road:"Western Express Highway",vehicle:"MH 02 FR 8421",severity:"Critical",time:"2 min ago",status:"Active",recommendation:"Schedule front suspension inspection within 24 hours."},
  {id:102,title:"Waterlogging route exposure",road:"SV Road · Santacruz",vehicle:"MH 01 TT 6240",severity:"Critical",time:"7 min ago",status:"Active",recommendation:"Reroute vehicle via Linking Road until water depth clears."},
  {id:103,title:"Repeated harsh braking",road:"LBS Marg · Ghatkopar",vehicle:"MH 04 LK 1098",severity:"High",time:"18 min ago",status:"Acknowledged",recommendation:"Review driver event and speed-breaker warning delivery."},
  {id:104,title:"Tyre grip estimate reduced",road:"Eastern Express Highway",vehicle:"MH 03 CP 7712",severity:"High",time:"34 min ago",status:"Active",recommendation:"Inspect tyre pressure and tread during the next depot stop."},
  {id:105,title:"Rough-road energy loss",road:"JVLR · Powai",vehicle:"MH 12 AX 5509",severity:"Medium",time:"1 hr ago",status:"Resolved",recommendation:"Route optimisation was applied automatically."},
];

const startingOrders:WorkOrder[]=[
  {id:"WO-2048",vehicle:"MH 02 FR 8421",task:"Front suspension and alignment inspection",owner:"Rahul S.",due:"Today · 16:30",status:"Open",priority:"Critical"},
  {id:"WO-2047",vehicle:"MH 04 LK 1098",task:"Tyre pressure and tread inspection",owner:"Priya M.",due:"Tomorrow · 10:00",status:"In progress",priority:"High"},
  {id:"WO-2046",vehicle:"MH 01 TT 6240",task:"Underbody impact assessment",owner:"Depot West",due:"02 Sep · 09:00",status:"Open",priority:"High"},
  {id:"WO-2041",vehicle:"MH 03 CP 7712",task:"Routine road-exposure inspection",owner:"Amit K.",due:"Completed",status:"Completed",priority:"Medium"},
];

const iconFor = (type:HazardType) => type==="Waterlogging"?Waves:type==="Speed breaker"?AlertTriangle:type==="Poor surface"?Construction:MapPin;
const tone = (severity:Severity) => severity.toLowerCase();

export default function Home(){
  const [activeView,setActiveView]=useState("Overview");
  const [typeFilter,setTypeFilter]=useState("All hazards");
  const [severityFilter,setSeverityFilter]=useState("All severity");
  const [fleetFilter,setFleetFilter]=useState("All fleets");
  const [alertFilter,setAlertFilter]=useState("All status");
  const [search,setSearch]=useState("");
  const [live,setLive]=useState(true);
  const [selected,setSelected]=useState<Hazard|null>(null);
  const [selectedVehicle,setSelectedVehicle]=useState<Vehicle|null>(null);
  const [alerts,setAlerts]=useState(startingAlerts);
  const [mobileNav,setMobileNav]=useState(false);
  const [reportOpen,setReportOpen]=useState(false);
  const [reportType,setReportType]=useState<HazardType>("Pothole");
  const [reportRoad,setReportRoad]=useState("");
  const [reportNotes,setReportNotes]=useState("");
  const [success,setSuccess]=useState("");
  const [darkMode,setDarkMode]=useState(false);
  const [customHazards,setCustomHazards]=useState<Hazard[]>([]);
  const [storageReady,setStorageReady]=useState(false);
  const [brand,setBrand]=useState<"BRI"|"Tata"|"Mahindra">("BRI");
  const [tourStep,setTourStep]=useState(-1);
  const [workOrders,setWorkOrders]=useState(startingOrders);
  const [installPrompt,setInstallPrompt]=useState<(Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>})|null>(null);

  useEffect(()=>{
    const saved=window.localStorage.getItem("bri-theme");
    const prefersDark=window.matchMedia("(prefers-color-scheme: dark)").matches;
    const shouldUseDark=saved?saved==="dark":prefersDark;
    setDarkMode(shouldUseDark);
    document.documentElement.classList.toggle("dark",shouldUseDark);
    try{
      const savedAlerts=window.localStorage.getItem("bri-alerts");
      const savedHazards=window.localStorage.getItem("bri-reports");
      const savedOrders=window.localStorage.getItem("bri-work-orders");
      const savedBrand=window.localStorage.getItem("bri-brand") as "BRI"|"Tata"|"Mahindra"|null;
      if(savedAlerts)setAlerts(JSON.parse(savedAlerts));
      if(savedHazards)setCustomHazards(JSON.parse(savedHazards));
      if(savedOrders)setWorkOrders(JSON.parse(savedOrders));
      if(savedBrand)setBrand(savedBrand);
    }catch{/* start with pilot defaults */}
    if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined);
    const captureInstall=(event:Event)=>{event.preventDefault();setInstallPrompt(event as Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>})};
    window.addEventListener("beforeinstallprompt",captureInstall);
    setStorageReady(true);
    return()=>{document.documentElement.classList.remove("dark");window.removeEventListener("beforeinstallprompt",captureInstall)};
  },[]);

  useEffect(()=>{if(storageReady)window.localStorage.setItem("bri-alerts",JSON.stringify(alerts))},[alerts,storageReady]);
  useEffect(()=>{if(storageReady)window.localStorage.setItem("bri-reports",JSON.stringify(customHazards))},[customHazards,storageReady]);
  useEffect(()=>{if(storageReady)window.localStorage.setItem("bri-work-orders",JSON.stringify(workOrders))},[workOrders,storageReady]);
  useEffect(()=>{if(storageReady)window.localStorage.setItem("bri-brand",brand)},[brand,storageReady]);

  const allHazards=useMemo(()=>[...customHazards,...hazards],[customHazards]);
  const filteredHazards=useMemo(()=>allHazards.filter(h=>(typeFilter==="All hazards"||h.type===typeFilter)&&(severityFilter==="All severity"||h.severity===severityFilter)),[allHazards,typeFilter,severityFilter]);
  const filteredVehicles=useMemo(()=>vehicles.filter(v=>(fleetFilter==="All fleets"||v.fleet===fleetFilter)&&(v.id.toLowerCase().includes(search.toLowerCase())||v.model.toLowerCase().includes(search.toLowerCase()))),[fleetFilter,search]);
  const filteredAlerts=alerts.filter(a=>alertFilter==="All status"||a.status===alertFilter);
  const activeAlerts=alerts.filter(a=>a.status!=="Resolved").length;
  const navItems=[{label:"Overview",icon:LayoutDashboard},{label:"Road network",icon:Map},{label:"Fleet insights",icon:Truck},{label:"Vehicle alerts",icon:Bell,badge:String(activeAlerts)},{label:"Maintenance",icon:ClipboardList},{label:"Simulator",icon:Calculator},{label:"Driver app",icon:Smartphone},{label:"Public works",icon:Building2},{label:"OEM integration",icon:Cpu},{label:"Settings",icon:Settings}];
  const tourViews=["Overview","Road network","Fleet insights","Simulator","Driver app","Public works","OEM integration"];

  function notify(message:string){setSuccess(message);window.setTimeout(()=>setSuccess(""),3200)}
  function exportData(){
    const rows=activeView==="Fleet insights"?vehicles.map(v=>[v.id,v.model,v.fleet,v.impacts,v.risk,v.health]):allHazards.map(h=>[h.type,h.severity,h.road,h.area,h.reports,h.confidence]);
    const header=activeView==="Fleet insights"?["Vehicle","Model","Fleet","Impacts","Risk","Health"]:["Hazard","Severity","Road","Area","Reports","Confidence"];
    const csv=[header,...rows].map(r=>r.map(String).map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n");
    const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));link.download=`bri-${activeView.toLowerCase().replaceAll(" ","-")}.csv`;link.click();URL.revokeObjectURL(link.href);notify("Operational data exported successfully");
  }
  function submitReport(){if(!reportRoad.trim()){notify("Add a road or landmark before submitting");return}const next:Hazard={id:Date.now(),type:reportType,severity:"High",road:reportRoad.trim(),area:"Community report",seen:"Just now",reports:1,confidence:72,x:34+(customHazards.length*13)%40,y:31+(customHazards.length*17)%42,note:reportNotes.trim()||"Field observation submitted for sensor verification."};setCustomHazards(list=>[next,...list]);setReportOpen(false);setReportRoad("");setReportNotes("");notify(`${reportType} report saved on this device and added to the map`)}
  function updateAlert(id:number,status:AlertRecord["status"]){setAlerts(list=>list.map(a=>a.id===id?{...a,status}:a));notify(status==="Resolved"?"Alert resolved and archived":"Alert acknowledged by operations")}
  function toggleTheme(){const next=!darkMode;setDarkMode(next);document.documentElement.classList.toggle("dark",next);window.localStorage.setItem("bri-theme",next?"dark":"light")}
  function beginTour(){setTourStep(0);setActiveView(tourViews[0])}
  function nextTour(){const next=tourStep+1;if(next>=tourViews.length){setTourStep(-1);notify("Guided product tour completed");return}setTourStep(next);setActiveView(tourViews[next])}
  function updateOrder(id:string,status:WorkOrder["status"]){setWorkOrders(list=>list.map(o=>o.id===id?{...o,status}:o));notify(`${id} moved to ${status.toLowerCase()}`)}
  async function installApp(){if(installPrompt){await installPrompt.prompt();const result=await installPrompt.userChoice;if(result.outcome==="accepted")setInstallPrompt(null)}else notify("Use your browser menu and choose ‘Install app’ or ‘Add to Home screen’")}
  function resetDemo(){["bri-alerts","bri-reports","bri-work-orders","bri-brand"].forEach(k=>window.localStorage.removeItem(k));setAlerts(startingAlerts);setCustomHazards([]);setWorkOrders(startingOrders);setBrand("BRI");notify("Demo data restored to its original state")}

  return <main className={`app-shell brand-${brand.toLowerCase()}`}>
    <aside className={`sidebar ${mobileNav?"mobile-open":""}`}>
      <div className="brand-row"><div className="brand-mark"><Route size={22}/></div><div><strong>{brand==="BRI"?"BRI":brand.toUpperCase()}</strong><span>{brand==="BRI"?"ROAD INTELLIGENCE":"POWERED BY BRI"}</span></div></div>
      <div className="pilot-chip"><span className="pulse-dot"/> Mumbai pilot · Live</div>
      <nav className="main-nav" aria-label="Primary navigation"><p>OPERATIONS</p>{navItems.map(({label,icon:Icon,badge})=><button key={label} className={activeView===label?"active":""} onClick={()=>{setActiveView(label);setMobileNav(false)}}><Icon size={18}/><span>{label}</span>{badge&&<em>{badge}</em>}</button>)}</nav>
      <div className="sidebar-spacer"/><div className="coverage-card"><div className="coverage-icon"><Navigation size={17}/></div><div><span>PILOT COVERAGE</span><strong>2,840 km</strong><small>mapped this week</small></div></div><div className="profile-row"><div className="avatar">AK</div><div><strong>Arjun Khanna</strong><span>Fleet operations</span></div><ChevronRight size={16}/></div>
    </aside>

    <section className="workspace">
      <header className="topbar"><Button variant="ghost" size="icon" className="menu-button" onClick={()=>setMobileNav(!mobileNav)} aria-label="Toggle menu"><Menu/></Button><div><p>CONTROL CENTRE <span>/</span> {activeView.toUpperCase()}</p><h1>{activeView}</h1></div><div className="topbar-actions"><div className="weather"><CloudRain size={17}/><span><strong>Moderate rain</strong>Mumbai · 27°C</span></div><div className="sync"><span className={live?"pulse-dot":"offline-dot"}/>{live?"Synced 14 sec ago":"Live feed paused"}</div><Button variant="outline" size="icon" className="theme-button" onClick={toggleTheme} aria-label={darkMode?"Switch to light mode":"Switch to dark mode"}>{darkMode?<Sun/>:<Moon/>}</Button><Button variant="outline" className="tour-button" onClick={beginTour}><Presentation/> Tour</Button><Button variant="outline" className="export-button" onClick={()=>window.print()}><Download/> Report</Button><Button className="report-button" onClick={()=>setReportOpen(true)}><Plus/> Report hazard</Button></div></header>
      <div className="content"><div className="notice"><Sparkles size={16}/><span><strong>Pilot simulation</strong> · Realistic demonstration data for OEM and fleet evaluation.</span><b>DEMO MODE</b></div>
        {activeView==="Overview"&&<OverviewView onOpenNetwork={()=>setActiveView("Road network")} onSelectHazard={setSelected}/>} 
        {activeView==="Road network"&&<RoadNetworkView filteredHazards={filteredHazards} typeFilter={typeFilter} setTypeFilter={setTypeFilter} severityFilter={severityFilter} setSeverityFilter={setSeverityFilter} live={live} setLive={setLive} onSelect={setSelected} exportData={exportData}/>} 
        {activeView==="Fleet insights"&&<FleetView fleetFilter={fleetFilter} setFleetFilter={setFleetFilter} search={search} setSearch={setSearch} vehicles={filteredVehicles} onSelect={setSelectedVehicle}/>} 
        {activeView==="Vehicle alerts"&&<AlertsView alerts={filteredAlerts} alertFilter={alertFilter} setAlertFilter={setAlertFilter} updateAlert={updateAlert}/>} 
        {activeView==="Maintenance"&&<MaintenanceView orders={workOrders} updateOrder={updateOrder}/>} 
        {activeView==="Simulator"&&<SimulatorView notify={notify}/>} 
        {activeView==="Driver app"&&<DriverAppView/>} 
        {activeView==="Public works"&&<PublicWorksView onSelectHazard={setSelected}/>} 
        {activeView==="OEM integration"&&<IntegrationView notify={notify}/>} 
        {activeView==="Settings"&&<SettingsView brand={brand} setBrand={setBrand} darkMode={darkMode} toggleTheme={toggleTheme} installApp={installApp} resetDemo={resetDemo}/>} 
      </div>
    </section>

    {tourStep>=0&&<div className="tour-overlay"><div><span>GUIDED TOUR · {tourStep+1}/{tourViews.length}</span><strong>{tourViews[tourStep]}</strong><p>{["Start with the executive health and impact summary.","Inspect and filter road hazards in real time.","Identify fleet exposure and maintenance risk.","Model ROI for an OEM or fleet pilot.","Preview the in-vehicle driver experience.","Prioritise government road-repair budgets.","Show exactly how vehicle signals connect."][tourStep]}</p></div><Button variant="ghost" onClick={()=>setTourStep(-1)}>Exit</Button><Button onClick={nextTour}>{tourStep===tourViews.length-1?"Finish":"Next"}<ChevronRight/></Button></div>}

    <HazardSheet selected={selected} setSelected={setSelected} notify={notify}/>
    <VehicleSheet vehicle={selectedVehicle} setVehicle={setSelectedVehicle} notify={notify}/>
    <Dialog open={reportOpen} onOpenChange={setReportOpen}><DialogContent className="report-dialog"><DialogHeader><DialogTitle>Report a road hazard</DialogTitle><DialogDescription>Add a field observation to the BRI verification queue.</DialogDescription></DialogHeader><div className="report-form"><label>Hazard type<Select value={reportType} onValueChange={v=>setReportType(v as HazardType)}><SelectTrigger className="form-control"><SelectValue/></SelectTrigger><SelectContent>{["Pothole","Speed breaker","Waterlogging","Poor surface"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label>Road or landmark<Input value={reportRoad} onChange={e=>setReportRoad(e.target.value)} placeholder="e.g. JVLR near Powai Lake"/></label><label>Field notes<Textarea value={reportNotes} onChange={e=>setReportNotes(e.target.value)} placeholder="Add lane, direction, visibility, or depth details"/></label><div className="sensor-note"><Activity size={17}/><span>Location, speed, and motion sensor evidence will be attached automatically.</span></div></div><DialogFooter><Button variant="outline" onClick={()=>setReportOpen(false)}>Cancel</Button><Button className="detail-primary" onClick={submitReport}>Submit report</Button></DialogFooter></DialogContent></Dialog>
    {success&&<div className="success-toast"><Check size={17}/><span>{success}</span><button onClick={()=>setSuccess("")} aria-label="Dismiss"><X size={15}/></button></div>}
  </main>;
}

function OverviewView({onOpenNetwork,onSelectHazard}:{onOpenNetwork:()=>void;onSelectHazard:(h:Hazard)=>void}){return <>
  <section className="kpi-grid"><Kpi icon={<AlertTriangle/>} iconTone="red" badge="+8.4%" badgeTone="bad" label="ACTIVE HAZARDS" value="1,247" unit="across network"/><Kpi icon={<CircleGauge/>} iconTone="amber" badge="+2.1 pts" badgeTone="good" label="ROAD HEALTH SCORE" value="71.4" unit="of 100"/><Kpi icon={<ShieldCheck/>} iconTone="teal" badge="+12.7%" badgeTone="good" label="HAZARDS AVOIDED" value="18,392" unit="this month"/><Kpi icon={<Zap/>} iconTone="blue" badge="8.6% saved" badgeTone="good" label="EV RANGE RECOVERED" value="4,820" unit="kWh estimated"/></section>
  <section className="overview-grid"><article className="command-card"><div className="panel-head"><div><p className="eyebrow">NETWORK COMMAND</p><h2>Road intelligence at a glance</h2></div><Button variant="outline" size="sm" onClick={onOpenNetwork}>Open live map <ChevronRight/></Button></div><div className="command-body"><div className="health-ring"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="49"/><circle className="value" cx="60" cy="60" r="49"/></svg><div><strong>71.4</strong><span>ROAD HEALTH</span></div></div><div className="health-copy"><Badge className="status-operational">NETWORK OPERATIONAL</Badge><h3>Conditions are stable, with monsoon risk concentrated in three western zones.</h3><p>BRI processed 4.8 million sensor events from 2,316 connected vehicles in the last 24 hours.</p><div className="outcome-row"><span><b>96.2%</b> detection confidence</span><span><b>41 sec</b> median alert time</span><span><b>2.3 km</b> advance warning</span></div></div></div></article>
    <article className="zones-card"><div className="panel-head"><div><p className="eyebrow">CITY HEALTH</p><h2>Monitored zones</h2></div></div><div className="zone-list">{[{n:"Western suburbs",s:63,t:"high"},{n:"Central corridor",s:74,t:"medium"},{n:"Eastern suburbs",s:78,t:"good"},{n:"South Mumbai",s:82,t:"good"}].map(z=><div key={z.n} className="zone-row"><div><strong>{z.n}</strong><span>{z.s}/100</span></div><Progress value={z.s}/><em className={z.t}>{z.t==="good"?"Stable":z.t==="high"?"Watch":"Moderate"}</em></div>)}</div></article></section>
  <section className="overview-bottom"><article className="chart-card"><div className="panel-head"><div><p className="eyebrow">7-DAY SIGNAL</p><h2>Hazards detected vs avoided</h2></div><div className="chart-key"><span><i className="detected"/>Detected</span><span><i className="avoided"/>Avoided</span></div></div><div className="dual-chart">{[{d:"MON",a:55,b:39},{d:"TUE",a:68,b:48},{d:"WED",a:47,b:35},{d:"THU",a:79,b:62},{d:"FRI",a:66,b:54},{d:"SAT",a:88,b:73},{d:"SUN",a:58,b:49}].map(i=><div key={i.d}><div className="dual-bars"><i style={{height:`${i.a}%`}}/><b style={{height:`${i.b}%`}}/></div><span>{i.d}</span></div>)}</div></article><article className="feed-card"><div className="panel-head"><div><p className="eyebrow">NEEDS ATTENTION</p><h2>Highest priority</h2></div></div><div className="hazard-list">{hazards.slice(0,3).map(h=><HazardRow key={h.id} hazard={h} onSelect={onSelectHazard}/>)}</div></article></section>
  </>}

function RoadNetworkView({filteredHazards,typeFilter,setTypeFilter,severityFilter,setSeverityFilter,live,setLive,onSelect,exportData}:{filteredHazards:Hazard[];typeFilter:string;setTypeFilter:(v:string)=>void;severityFilter:string;setSeverityFilter:(v:string)=>void;live:boolean;setLive:(v:boolean)=>void;onSelect:(h:Hazard)=>void;exportData:()=>void}){const [heatmap,setHeatmap]=useState(false);const [history,setHistory]=useState([24]);return <>
  <section className="network-summary"><span><b>{filteredHazards.length}</b> visible pilot hazards</span><span><b>2,316</b> sensor vehicles online</span><span><b>98.1%</b> ingestion success</span><span><b>41 sec</b> median alert latency</span></section>
  <section className="main-grid"><article className="map-card"><div className="panel-head"><div><p className="eyebrow">LIVE ROAD NETWORK</p><h2>Mumbai hazard map</h2></div><div className="filters"><Select value={typeFilter} onValueChange={setTypeFilter}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["All hazards","Pothole","Speed breaker","Waterlogging","Poor surface"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={severityFilter} onValueChange={setSeverityFilter}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["All severity","Critical","High","Medium"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><label className="live-toggle">Heatmap <Switch checked={heatmap} onCheckedChange={setHeatmap}/></label><label className="live-toggle">Live <Switch checked={live} onCheckedChange={setLive}/></label></div></div><RoadMap hazards={filteredHazards} onSelect={onSelect} heatmap={heatmap}/><div className="time-slider"><span>HISTORY</span><Slider value={history} onValueChange={setHistory} min={1} max={168}/><b>Last {history[0]} hours</b></div></article><aside className="feed-card"><div className="panel-head"><div><p className="eyebrow">LIVE FEED</p><h2>Priority hazards</h2></div><button className="text-button" onClick={exportData}>Export <Download size={14}/></button></div><div className="hazard-list">{filteredHazards.slice(0,5).map(h=><HazardRow key={h.id} hazard={h} onSelect={onSelect}/>)}{!filteredHazards.length&&<div className="empty-state"><ShieldCheck/><strong>No matching hazards</strong><span>Try widening your filters.</span></div>}</div><div className="rain-risk"><CloudRain/><div><strong>Monsoon risk rising</strong><span>3 zones may waterlog in the next 45 min</span></div><ChevronRight/></div></aside></section>
  <section className="registry-card"><div className="panel-head"><div><p className="eyebrow">HAZARD REGISTRY</p><h2>Verified road events</h2></div><span className="updated-label">Updated just now</span></div><Table><TableHeader><TableRow><TableHead>Hazard</TableHead><TableHead>Location</TableHead><TableHead>Severity</TableHead><TableHead>Reports</TableHead><TableHead>Confidence</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{filteredHazards.map(h=><TableRow key={h.id}><TableCell><strong>{h.type}</strong></TableCell><TableCell>{h.road}<small>{h.area}</small></TableCell><TableCell><Badge className={tone(h.severity)}>{h.severity}</Badge></TableCell><TableCell>{h.reports}</TableCell><TableCell>{h.confidence}%</TableCell><TableCell><Button size="sm" variant="ghost" onClick={()=>onSelect(h)}>Inspect <ChevronRight/></Button></TableCell></TableRow>)}</TableBody></Table></section>
  </>}

function FleetView({fleetFilter,setFleetFilter,search,setSearch,vehicles,onSelect}:{fleetFilter:string;setFleetFilter:(v:string)=>void;search:string;setSearch:(v:string)=>void;vehicles:Vehicle[];onSelect:(v:Vehicle)=>void}){return <>
  <section className="kpi-grid"><Kpi icon={<Truck/>} iconTone="teal" badge="94.7%" badgeTone="good" label="VEHICLES ONLINE" value="2,316" unit="of 2,446"/><Kpi icon={<Wrench/>} iconTone="red" badge="12 urgent" badgeTone="bad" label="INSPECTION QUEUE" value="38" unit="vehicles"/><Kpi icon={<Fuel/>} iconTone="blue" badge="+3.1%" badgeTone="good" label="FLEET EFFICIENCY" value="6.4" unit="km/kWh"/><Kpi icon={<ShieldCheck/>} iconTone="amber" badge="−6.2%" badgeTone="good" label="SEVERE IMPACTS" value="3,842" unit="this week"/></section>
  <section className="fleet-analytics"><article className="chart-card"><div className="panel-head"><div><p className="eyebrow">FLEET EXPOSURE</p><h2>Severe impacts, last 7 days</h2></div><div className="chart-total"><strong>3,842</strong><span><TrendingDown/> 6.2% vs prior week</span></div></div><div className="bar-chart">{[{d:"MON",v:56,n:486},{d:"TUE",v:70,n:602},{d:"WED",v:43,n:371},{d:"THU",v:82,n:704},{d:"FRI",v:66,n:568},{d:"SAT",v:91,n:783},{d:"SUN",v:52,n:328}].map(i=><div key={i.d} className="bar-column"><span>{i.n}</span><div className="bar-track"><div style={{height:`${i.v}%`}}/></div><small>{i.d}</small></div>)}</div></article><article className="savings-card"><div className="panel-head"><div><p className="eyebrow">PREDICTED VALUE</p><h2>Monthly fleet savings</h2></div></div><div className="savings-body"><strong>₹18.6L</strong><span>estimated cost avoided</span><div className="savings-row"><div><i className="teal"><Wrench/></i><span>Maintenance<b>₹8.2L</b></span></div><div><i className="blue"><Zap/></i><span>Energy<b>₹6.7L</b></span></div><div><i className="orange"><Navigation/></i><span>Downtime<b>₹3.7L</b></span></div></div></div></article></section>
  <section className="registry-card"><div className="panel-head fleet-tools"><div><p className="eyebrow">VEHICLE HEALTH</p><h2>Maintenance priority</h2></div><div className="table-filters"><label><Search/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search vehicle"/></label><Select value={fleetFilter} onValueChange={setFleetFilter}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["All fleets","Mumbai EV Pilot","Last-mile West","Field Operations"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div></div><Table><TableHeader><TableRow><TableHead>Vehicle</TableHead><TableHead>Fleet</TableHead><TableHead>Severe impacts</TableHead><TableHead>Health</TableHead><TableHead>Risk</TableHead><TableHead>Status</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{vehicles.map(v=><TableRow key={v.id}><TableCell><strong>{v.id}</strong><small>{v.model}</small></TableCell><TableCell>{v.fleet}</TableCell><TableCell>{v.impacts}</TableCell><TableCell><div className="health-cell"><Progress value={v.health}/><span>{v.health}%</span></div></TableCell><TableCell><Badge className={tone(v.risk)}>{v.risk}</Badge></TableCell><TableCell>{v.status}</TableCell><TableCell><Button size="sm" variant="ghost" onClick={()=>onSelect(v)}>Open <ChevronRight/></Button></TableCell></TableRow>)}</TableBody></Table>{!vehicles.length&&<div className="empty-state"><Search/><strong>No vehicles found</strong><span>Try another registration or fleet.</span></div>}</section>
  </>}

function AlertsView({alerts,alertFilter,setAlertFilter,updateAlert}:{alerts:AlertRecord[];alertFilter:string;setAlertFilter:(v:string)=>void;updateAlert:(id:number,status:AlertRecord["status"])=>void}){return <>
  <section className="alert-summary"><article><span className="critical"><AlertTriangle/></span><div><b>2</b><small>Critical active</small></div></article><article><span className="high"><Bell/></span><div><b>3</b><small>Awaiting action</small></div></article><article><span className="medium"><Activity/></span><div><b>41 sec</b><small>Median response</small></div></article><article><span className="good"><ShieldCheck/></span><div><b>94%</b><small>Resolved in SLA</small></div></article></section>
  <section className="alerts-layout"><article className="alerts-card"><div className="panel-head"><div><p className="eyebrow">OPERATIONS QUEUE</p><h2>Vehicle alerts</h2></div><Select value={alertFilter} onValueChange={setAlertFilter}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["All status","Active","Acknowledged","Resolved"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div><div className="alert-list">{alerts.map(a=><div className={`alert-item ${tone(a.severity)}`} key={a.id}><div className="alert-symbol"><AlertTriangle/></div><div className="alert-main"><div><Badge className={tone(a.severity)}>{a.severity}</Badge><span>{a.time}</span></div><h3>{a.title}</h3><p>{a.road} · {a.vehicle}</p><small>{a.recommendation}</small></div><div className="alert-actions"><em className={a.status.toLowerCase()}>{a.status}</em>{a.status==="Active"&&<Button size="sm" variant="outline" onClick={()=>updateAlert(a.id,"Acknowledged")}>Acknowledge</Button>}{a.status!=="Resolved"&&<Button size="sm" onClick={()=>updateAlert(a.id,"Resolved")}><Check/> Resolve</Button>}</div></div>)}{!alerts.length&&<div className="empty-state"><ShieldCheck/><strong>Queue is clear</strong><span>No alerts match this status.</span></div>}</div></article><aside className="response-card"><div className="panel-head"><div><p className="eyebrow">RESPONSE HEALTH</p><h2>Today&apos;s SLA</h2></div></div><div className="sla-score"><strong>94%</strong><span>within response target</span></div><div className="sla-list"><div><span>Critical · 5 min</span><Progress value={96}/><b>96%</b></div><div><span>High · 30 min</span><Progress value={92}/><b>92%</b></div><div><span>Medium · 2 hr</span><Progress value={99}/><b>99%</b></div></div><div className="response-note"><TrendingUp/><span><b>7% faster</b> than the previous 30-day average</span></div></aside></section>
  </>}

function MaintenanceView({orders,updateOrder}:{orders:WorkOrder[];updateOrder:(id:string,status:WorkOrder["status"])=>void}){const [status,setStatus]=useState("All status");const shown=orders.filter(o=>status==="All status"||o.status===status);return <>
  <section className="kpi-grid"><Kpi icon={<Wrench/>} iconTone="red" badge="3 due today" badgeTone="bad" label="OPEN WORK ORDERS" value={String(orders.filter(o=>o.status!=="Completed").length)} unit="pilot fleet"/><Kpi icon={<Activity/>} iconTone="amber" badge="−9.4%" badgeTone="good" label="AVG. IMPACT LOAD" value="286" unit="events/vehicle"/><Kpi icon={<CalendarCheck/>} iconTone="teal" badge="94% SLA" badgeTone="good" label="COMPLETED" value="27" unit="this month"/><Kpi icon={<IndianRupee/>} iconTone="blue" badge="predicted" badgeTone="good" label="FAILURE COST AVOIDED" value="₹8.2L" unit="this month"/></section>
  <section className="maintenance-layout"><article className="registry-card"><div className="panel-head"><div><p className="eyebrow">MAINTENANCE OPERATIONS</p><h2>Work-order board</h2></div><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["All status","Open","In progress","Completed"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div><div className="work-order-list">{shown.map(o=><div className="work-order" key={o.id}><div className={`order-priority ${tone(o.priority)}`}><Wrench/></div><div className="order-copy"><span>{o.id} · {o.vehicle}</span><strong>{o.task}</strong><small>{o.owner} · {o.due}</small></div><Badge className={tone(o.priority)}>{o.priority}</Badge><Select value={o.status} onValueChange={v=>updateOrder(o.id,v as WorkOrder["status"])}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Open","In progress","Completed"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>)}</div></article><aside className="maintenance-plan"><div className="panel-head"><div><p className="eyebrow">PREDICTIVE PLAN</p><h2>Next 14 days</h2></div></div><div className="plan-calendar">{[{d:"01",n:3},{d:"02",n:5},{d:"03",n:2},{d:"04",n:7},{d:"05",n:4},{d:"06",n:1},{d:"07",n:6}].map(i=><div key={i.d}><span>SEP {i.d}</span><b style={{height:`${i.n*9}px`}}/><small>{i.n} jobs</small></div>)}</div><div className="plan-note"><ShieldCheck/><div><strong>Capacity is sufficient</strong><span>Projected workshop load remains below 82%.</span></div></div></aside></section>
  </>}

function SimulatorView({notify}:{notify:(m:string)=>void}){const [scenario,setScenario]=useState("Urban monsoon");const [fleetSize,setFleetSize]=useState([500]);const [dailyKm,setDailyKm]=useState([120]);const [license,setLicense]=useState([1000]);const multiplier=scenario==="Urban monsoon"?1.25:scenario==="Highway freight"?1.55:.82;const annualKm=fleetSize[0]*dailyKm[0]*300;const maintenance=Math.round(annualKm*.058*multiplier);const energy=Math.round(annualKm*.014);const licence=fleetSize[0]*license[0];const net=maintenance+energy-licence;return <>
  <section className="simulator-hero"><div><Badge className="status-operational">INTERACTIVE BUSINESS CASE</Badge><h2>Model the value of a BRI pilot.</h2><p>Adjust the fleet and operating environment to estimate annual maintenance, energy, and platform economics.</p></div><div className="scenario-tabs">{["Urban monsoon","Highway freight","City EV fleet"].map(v=><button key={v} className={scenario===v?"active":""} onClick={()=>setScenario(v)}>{v}</button>)}</div></section>
  <section className="simulator-grid"><article className="calculator-card"><div className="panel-head"><div><p className="eyebrow">INPUTS</p><h2>Pilot assumptions</h2></div></div><div className="slider-list"><SliderField label="Fleet size" value={fleetSize} setValue={setFleetSize} min={50} max={5000} step={50} suffix="vehicles"/><SliderField label="Average distance" value={dailyKm} setValue={setDailyKm} min={30} max={400} step={10} suffix="km/day"/><SliderField label="BRI licence" value={license} setValue={setLicense} min={800} max={2500} step={100} prefix="₹" suffix="/vehicle"/></div></article><article className="roi-card"><div className="panel-head"><div><p className="eyebrow">ANNUAL ESTIMATE</p><h2>Business impact</h2></div></div><div className="roi-total"><span>NET CUSTOMER VALUE</span><strong>₹{(net/100000).toFixed(1)}L</strong><em>{Math.max(0,Math.round(net/licence*100))}% estimated ROI</em></div><div className="roi-breakdown"><div><Wrench/><span>Maintenance avoided<b>₹{(maintenance/100000).toFixed(1)}L</b></span></div><div><Zap/><span>Energy recovered<b>₹{(energy/100000).toFixed(1)}L</b></span></div><div><Cpu/><span>Platform cost<b>−₹{(licence/100000).toFixed(1)}L</b></span></div></div><Button onClick={()=>notify("ROI assumptions copied into the executive report")}><Presentation/> Add to executive report</Button></article></section>
  <section className="route-compare"><div className="panel-head"><div><p className="eyebrow">ROUTE INTELLIGENCE</p><h2>Fastest route vs BRI recommended</h2></div><Badge className="status-operational">SIMULATED</Badge></div><div className="route-options"><article><div><span>A</span><strong>Fastest route</strong><Badge variant="outline">Maps default</Badge></div><div className="route-line risky"><i/><i/><i/><i/><i/></div><dl><div><dt>Time</dt><dd>42 min</dd></div><div><dt>Severe hazards</dt><dd>8</dd></div><div><dt>Energy use</dt><dd>13.8 kWh</dd></div><div><dt>Impact risk</dt><dd className="risk-text">High</dd></div></dl></article><article className="recommended"><div><span>B</span><strong>BRI safe route</strong><Badge>Recommended</Badge></div><div className="route-line safe"><i/><i/><i/><i/><i/></div><dl><div><dt>Time</dt><dd>46 min</dd></div><div><dt>Severe hazards</dt><dd>1</dd></div><div><dt>Energy use</dt><dd>12.6 kWh</dd></div><div><dt>Impact risk</dt><dd className="safe-text">Low</dd></div></dl></article></div></section>
  </>}

function SliderField({label,value,setValue,min,max,step,prefix="",suffix}:{label:string;value:number[];setValue:(v:number[])=>void;min:number;max:number;step:number;prefix?:string;suffix:string}){return <label><div><span>{label}</span><strong>{prefix}{value[0].toLocaleString()} <small>{suffix}</small></strong></div><Slider value={value} onValueChange={setValue} min={min} max={max} step={step}/><div className="slider-range"><span>{prefix}{min}</span><span>{prefix}{max.toLocaleString()}</span></div></label>}

function DriverAppView(){const [hindi,setHindi]=useState(false);const [warning,setWarning]=useState(true);const t=hindi?{safe:"सुरक्षित मार्ग",alert:"आगे गड्ढा",distance:"180 मीटर आगे",slow:"गति कम करें",trip:"आज की यात्रा",avoided:"7 खतरे टाले गए",energy:"8% ऊर्जा बची",start:"मार्ग शुरू करें"}:{safe:"Safer route",alert:"Pothole ahead",distance:"180 metres ahead",slow:"Reduce speed",trip:"Today’s drive",avoided:"7 hazards avoided",energy:"8% energy saved",start:"Start safer route"};return <>
  <section className="driver-layout"><div className="phone-stage"><div className="phone-shell"><div className="phone-top"><span>9:41</span><i/><span>5G · 92%</span></div><div className="driver-map"><div className="driver-route"><i/><i/><i/><i/><i/></div><div className="car-dot"><Navigation/></div>{warning&&<div className="driver-warning"><AlertTriangle/><div><strong>{t.alert}</strong><span>{t.distance} · {t.slow}</span></div><button onClick={()=>setWarning(false)}><X/></button></div>}</div><div className="driver-bottom"><span>{t.safe}</span><h3>Andheri → BKC</h3><div className="driver-stats"><div><strong>46 min</strong><span>ETA</span></div><div><strong>1</strong><span>hazard</span></div><div><strong>−8%</strong><span>energy</span></div></div><Button onClick={()=>setWarning(true)}><Navigation/> {t.start}</Button></div></div></div><div className="driver-copy"><Badge className="status-operational">CONSUMER EXPERIENCE</Badge><h2>Road intelligence drivers can feel.</h2><p>A calm, voice-friendly interface warns without distracting. It explains the value after each trip instead of overwhelming the driver with raw road data.</p><label className="language-toggle"><Languages/><span>Driver language</span><Button variant={hindi?"outline":"default"} size="sm" onClick={()=>setHindi(false)}>EN</Button><Button variant={hindi?"default":"outline"} size="sm" onClick={()=>setHindi(true)}>हिं</Button></label><div className="trip-summary"><strong>{t.trip}</strong><div><span><ShieldCheck/>{t.avoided}</span><span><Zap/>{t.energy}</span></div></div><div className="driver-features"><span><Check/> Spoken hazard warnings</span><span><Check/> Offline rural-road mode</span><span><Check/> One-tap community reporting</span><span><Check/> Trip safety score</span></div></div></section>
  </>}

function SettingsView({brand,setBrand,darkMode,toggleTheme,installApp,resetDemo}:{brand:"BRI"|"Tata"|"Mahindra";setBrand:(v:"BRI"|"Tata"|"Mahindra")=>void;darkMode:boolean;toggleTheme:()=>void;installApp:()=>void;resetDemo:()=>void}){const [autoWarn,setAutoWarn]=useState(true);const [monsoon,setMonsoon]=useState(true);const [threshold,setThreshold]=useState([72]);return <section className="settings-grid"><article className="settings-card"><div className="panel-head"><div><p className="eyebrow">WHITE LABEL</p><h2>OEM branding</h2></div></div><div className="settings-body"><label>Active brand<Select value={brand} onValueChange={v=>setBrand(v as "BRI"|"Tata"|"Mahindra")}><SelectTrigger className="form-control"><SelectValue/></SelectTrigger><SelectContent>{["BRI","Tata","Mahindra"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><div className="brand-preview"><div className="brand-mark"><Route/></div><div><strong>{brand==="BRI"?"BRI":brand.toUpperCase()}</strong><span>{brand==="BRI"?"ROAD INTELLIGENCE":"POWERED BY BRI"}</span></div></div><small>Changes are applied across the dashboard and saved on this device.</small></div></article><article className="settings-card"><div className="panel-head"><div><p className="eyebrow">ALERT POLICY</p><h2>Detection thresholds</h2></div></div><div className="settings-body toggle-settings"><div><span><strong>Automatic route warnings</strong><small>Warn connected vehicles without operator approval</small></span><Switch checked={autoWarn} onCheckedChange={setAutoWarn}/></div><div><span><strong>Monsoon prediction</strong><small>Enable rainfall-weighted waterlogging risk</small></span><Switch checked={monsoon} onCheckedChange={setMonsoon}/></div><label><span><strong>Minimum confidence</strong><small>Publish hazards above {threshold[0]}%</small></span><Slider value={threshold} onValueChange={setThreshold} min={50} max={99}/></label></div></article><article className="settings-card"><div className="panel-head"><div><p className="eyebrow">APP EXPERIENCE</p><h2>Appearance and installation</h2></div></div><div className="settings-body action-settings"><button onClick={toggleTheme}><span>{darkMode?<Sun/>:<Moon/>}<b>{darkMode?"Use light mode":"Use dark mode"}</b></span><ChevronRight/></button><button onClick={installApp}><span><Smartphone/><b>Install BRI app</b></span><ChevronRight/></button><button onClick={()=>window.print()}><span><Presentation/><b>Print executive report</b></span><ChevronRight/></button></div></article><article className="settings-card danger-card"><div className="panel-head"><div><p className="eyebrow">DEMO CONTROL</p><h2>Reset local activity</h2></div></div><div className="settings-body"><p>Restore alerts, maintenance jobs, reports, and branding to the original demonstration state.</p><Button variant="outline" onClick={resetDemo}><RotateCcw/> Reset demo</Button></div></article></section>}

function PublicWorksView({onSelectHazard}:{onSelectHazard:(h:Hazard)=>void}){const wards=[{ward:"K/West · Andheri",hazards:184,score:46,cost:"₹2.8 Cr",priority:"Critical"},{ward:"H/West · Bandra",hazards:132,score:58,cost:"₹1.9 Cr",priority:"High"},{ward:"L · Kurla",hazards:119,score:62,cost:"₹1.6 Cr",priority:"High"},{ward:"S · Bhandup",hazards:86,score:69,cost:"₹1.1 Cr",priority:"Medium"},{ward:"A · Colaba",hazards:41,score:84,cost:"₹0.4 Cr",priority:"Medium"}];function downloadBrief(){const text=["BRI Municipal Repair Priority Brief","Pilot: Mumbai","","Priority: K/West · Andheri","Verified hazards: 184","Health score: 46/100","Estimated package: ₹2.8 Cr","Expected severe-impact reduction: 41%"].join("\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([text],{type:"text/plain"}));link.download="BRI-municipal-priority-brief.txt";link.click();URL.revokeObjectURL(link.href)}return <>
  <section className="kpi-grid"><Kpi icon={<Construction/>} iconTone="red" badge="18 urgent" badgeTone="bad" label="REPAIR CANDIDATES" value="462" unit="verified segments"/><Kpi icon={<IndianRupee/>} iconTone="amber" badge="AI estimate" badgeTone="good" label="ESTIMATED BACKLOG" value="₹7.8 Cr" unit="pilot zones"/><Kpi icon={<ShieldCheck/>} iconTone="teal" badge="+11.6%" badgeTone="good" label="SAFETY IMPACT" value="3,240" unit="daily vehicles"/><Kpi icon={<CloudRain/>} iconTone="blue" badge="3 watch" badgeTone="bad" label="MONSOON ZONES" value="12" unit="actively monitored"/></section>
  <section className="works-grid"><article className="registry-card works-table"><div className="panel-head"><div><p className="eyebrow">REPAIR PRIORITISATION</p><h2>Ward action plan</h2></div><Badge className="status-operational">IMPACT-WEIGHTED</Badge></div><Table><TableHeader><TableRow><TableHead>Ward</TableHead><TableHead>Hazards</TableHead><TableHead>Health score</TableHead><TableHead>Budget estimate</TableHead><TableHead>Priority</TableHead></TableRow></TableHeader><TableBody>{wards.map(w=><TableRow key={w.ward}><TableCell><strong>{w.ward}</strong></TableCell><TableCell>{w.hazards}</TableCell><TableCell><div className="health-cell"><Progress value={w.score}/><span>{w.score}</span></div></TableCell><TableCell>{w.cost}</TableCell><TableCell><Badge className={w.priority.toLowerCase()}>{w.priority}</Badge></TableCell></TableRow>)}</TableBody></Table></article><aside className="impact-card"><div className="panel-head"><div><p className="eyebrow">RECOMMENDED PACKAGE</p><h2>Western suburbs</h2></div></div><div className="impact-body"><div className="impact-score"><strong>87</strong><span>PRIORITY INDEX</span></div><h3>Repair 18 high-impact segments first</h3><p>Prioritisation combines severity, vehicle volume, repeat reports, rain exposure, and public-safety impact.</p><div className="impact-metrics"><span><b>41%</b> fewer severe impacts</span><span><b>₹72L</b> avoided vehicle damage</span><span><b>28 days</b> expected payback</span></div><Button onClick={()=>onSelectHazard(hazards[0])}>Inspect highest-risk segment <ChevronRight/></Button></div></aside></section>
  <section className="procurement-strip"><Building2/><div><strong>Export-ready for municipal review</strong><span>The ward plan, evidence count, confidence score, and estimated repair value can be packaged for tender prioritisation when verified data is connected.</span></div><Button variant="outline" onClick={downloadBrief}><Download/> Download sample brief</Button></section>
  </>}

function IntegrationView({notify}:{notify:(m:string)=>void}){const [running,setRunning]=useState(false);const [events,setEvents]=useState(0);const sample=`POST /v1/telemetry/events\n{\n  "vehicle_id": "MH02FR8421",\n  "timestamp": "2026-08-31T12:30:00Z",\n  "gps": { "lat": 19.1197, "lng": 72.8464 },\n  "speed_kph": 38.2,\n  "vertical_accel_g": 1.84,\n  "abs_active": false\n}`;function run(){setRunning(true);setEvents(0);let count=0;const timer=window.setInterval(()=>{count+=Math.floor(180+Math.random()*140);setEvents(count);if(count>1200){window.clearInterval(timer);setRunning(false);notify("Demo ingestion completed: sensor events fused into 6 verified hazards")}},220)}function copySample(){navigator.clipboard?.writeText(sample);notify("Sample telemetry request copied")}return <>
  <section className="integration-hero"><div><Badge className="status-operational">PILOT-READY ARCHITECTURE</Badge><h2>Connect vehicle signals when the OEM is ready.</h2><p>The interface and event contract are prepared for CAN bus, GPS, accelerometer, suspension, ABS, camera, and connectivity inputs. No live vehicle data is connected yet.</p><div className="integration-actions"><Button onClick={run} disabled={running}>{running?<Activity className="spin"/>:<Radio/>}{running?"Processing demo stream":"Run simulated sensor stream"}</Button><Button variant="outline" onClick={()=>notify("Sample event schema downloaded")}><Download/> Download event schema</Button></div></div><div className="stream-console"><div><span/><b>EDGE-01 · SIMULATION</b><em>{running?"STREAMING":"READY"}</em></div><strong>{events.toLocaleString()}</strong><span>sensor events processed</span><div className="signal-line">{[35,62,44,82,51,91,68,73,46,88,64,96].map((n,i)=><i key={i} style={{height:`${running?n:24}%`}}/>)}</div></div></section>
  <section className="integration-grid">{[{icon:Activity,title:"Motion & suspension",copy:"Vertical acceleration, suspension travel, pitch, roll, and impact signatures.",state:"Schema ready"},{icon:Navigation,title:"Location & speed",copy:"GPS trace, heading, vehicle speed, route context, and map matching.",state:"Schema ready"},{icon:Gauge,title:"Vehicle dynamics",copy:"ABS activity, wheel speed, braking intensity, and steering inputs.",state:"Schema ready"},{icon:Wifi,title:"Offline sync",copy:"Local event queue, compression, deduplication, and delayed secure upload.",state:"Prototype ready"}].map(({icon:Icon,title,copy,state})=><article key={title}><i><Icon/></i><div><strong>{title}</strong><p>{copy}</p><span><Check/> {state}</span></div></article>)}</section>
  <section className="pipeline-card"><div className="panel-head"><div><p className="eyebrow">REFERENCE FLOW</p><h2>Vehicle-to-intelligence pipeline</h2></div></div><div className="pipeline-flow"><div><Smartphone/><strong>Vehicle edge</strong><span>Detect & compress</span></div><ChevronRight/><div><Radio/><strong>Secure ingestion</strong><span>Validate & dedupe</span></div><ChevronRight/><div><Database/><strong>Road intelligence</strong><span>Fuse & score</span></div><ChevronRight/><div><Bell/><strong>Action layer</strong><span>Warn & optimise</span></div></div><div className="readiness-list"><span><Check/> Event schema defined</span><span><Check/> Offline queue model</span><span><Check/> Hazard confidence scoring</span><span><Check/> OEM-branded dashboard</span><span className="waiting"><X/> Live CAN mapping</span><span className="waiting"><X/> Production security review</span></div></section>
  <section className="api-card"><div><p className="eyebrow">DEVELOPER HANDOFF</p><h2>Telemetry event API</h2><p>Illustrative contract for OEM engineering evaluation. Authentication and final signal mapping will be agreed during the pilot.</p><div className="api-facts"><span><b>Protocol</b>HTTPS / JSON</span><span><b>Batching</b>Up to 500 events</span><span><b>Offline queue</b>72 hours</span></div></div><div className="code-sample"><button onClick={copySample}><Copy/> Copy</button><pre>{sample}</pre></div></section>
  </>}

function Kpi({icon,iconTone,badge,badgeTone,label,value,unit}:{icon:React.ReactNode;iconTone:string;badge:string;badgeTone:string;label:string;value:string;unit:string}){return <article className="kpi-card"><div className="kpi-top"><div className={`kpi-icon ${iconTone}`}>{icon}</div><Badge className={`trend-badge ${badgeTone}`}>{badge}</Badge></div><p>{label}</p><div className="kpi-value">{value} <span>{unit}</span></div><div className={`spark-line ${iconTone}`}><i/><i/><i/><i/><i/><i/><i/></div></article>}
function HazardRow({hazard,onSelect}:{hazard:Hazard;onSelect:(h:Hazard)=>void}){const Icon=iconFor(hazard.type);return <button className="hazard-row" onClick={()=>onSelect(hazard)}><span className={`hazard-icon ${tone(hazard.severity)}`}><Icon/></span><span className="hazard-copy"><strong>{hazard.type}</strong><small>{hazard.road} · {hazard.area}</small><em>{hazard.reports} reports · {hazard.seen}</em></span><span className={`severity-label ${tone(hazard.severity)}`}>{hazard.severity}</span></button>}
function RoadMap({hazards,onSelect,heatmap=false}:{hazards:Hazard[];onSelect:(h:Hazard)=>void;heatmap?:boolean}){return <div className="map-canvas"><svg className="road-map" viewBox="0 0 900 520" preserveAspectRatio="none" aria-hidden="true"><path className="water" d="M0 20 C130 80 70 210 160 268 C260 330 265 440 220 520 L0 520Z"/><g className="minor-roads"><path d="M130 30L840 480M10 110L850 210M200 0L500 520M90 410L830 70M320 0L740 520M0 300L900 360M420 0L120 520M580 0L900 280"/></g><g className="major-roads"><path d="M80 40C220 125 185 250 350 300S600 370 840 480"/><path d="M30 390C230 330 300 160 500 145S720 190 875 85"/><path d="M290 20C360 160 455 205 520 350S650 470 850 505"/></g><g className="rail-lines"><path d="M170 0L300 520M600 0L690 520"/></g></svg>{heatmap&&<div className="heatmap-layer">{hazards.map(h=><i key={h.id} className={tone(h.severity)} style={{left:`${h.x}%`,top:`${h.y}%`}}/>)}</div>}<div className="map-label label-sea">ARABIAN SEA</div><div className="map-label label-andheri">ANDHERI</div><div className="map-label label-powai">POWAI</div><div className="map-label label-bandra">BANDRA</div><div className="map-label label-ghatkopar">GHATKOPAR</div>{!heatmap&&hazards.map(h=>{const Icon=iconFor(h.type);return <button key={h.id} className={`map-marker ${tone(h.severity)}`} style={{left:`${h.x}%`,top:`${h.y}%`}} onClick={()=>onSelect(h)} aria-label={`${h.severity} ${h.type} on ${h.road}`}><Icon/></button>})}<div className="map-tools"><button aria-label="Recenter"><Crosshair/></button><span/><button>+</button><button>−</button></div><div className="map-legend"><span><i className="dot critical"/>Critical</span><span><i className="dot high"/>High</span><span><i className="dot medium"/>Medium</span><b>{hazards.length} visible</b></div></div>}

function HazardSheet({selected,setSelected,notify}:{selected:Hazard|null;setSelected:(h:Hazard|null)=>void;notify:(m:string)=>void}){return <Sheet open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><SheetContent className="hazard-sheet">{selected&&<><SheetHeader><div className={`detail-icon ${tone(selected.severity)}`}>{(()=>{const Icon=iconFor(selected.type);return <Icon/>})()}</div><SheetTitle>{selected.type}</SheetTitle><SheetDescription>{selected.road} · {selected.area}</SheetDescription></SheetHeader><div className="detail-body"><div className="detail-status"><Badge className={tone(selected.severity)}>{selected.severity}</Badge><span>Detected {selected.seen}</span></div><p>{selected.note}</p><div className="detail-grid"><div><span>CONFIDENCE</span><strong>{selected.confidence}%</strong></div><div><span>VEHICLE REPORTS</span><strong>{selected.reports}</strong></div><div><span>ROAD</span><strong>{selected.road}</strong></div><div><span>ZONE</span><strong>{selected.area}</strong></div></div><div className="hazard-timeline"><span>EVENT TIMELINE</span><div><i className="done"/><b>First detected</b><em>08:42</em></div><div><i className="done"/><b>Multi-vehicle verified</b><em>08:44</em></div><div><i/><b>Road inspection</b><em>Pending</em></div></div><div className="action-callout"><Gauge/><div><strong>Recommended action</strong><span>Reduce approach speed and reroute high-load vehicles until verified clear.</span></div></div><Button className="detail-primary" onClick={()=>notify("Route warning sent to 184 nearby vehicles")}><Navigation/> Send route warning</Button><Button variant="outline" className="detail-secondary" onClick={()=>notify("Road inspection request created")}>Mark for road inspection</Button></div></>}</SheetContent></Sheet>}
function VehicleSheet({vehicle,setVehicle,notify}:{vehicle:Vehicle|null;setVehicle:(v:Vehicle|null)=>void;notify:(m:string)=>void}){return <Sheet open={!!vehicle} onOpenChange={o=>!o&&setVehicle(null)}><SheetContent className="hazard-sheet">{vehicle&&<><SheetHeader><div className={`detail-icon ${tone(vehicle.risk)}`}><Truck/></div><SheetTitle>{vehicle.id}</SheetTitle><SheetDescription>{vehicle.model} · {vehicle.fleet}</SheetDescription></SheetHeader><div className="detail-body"><div className="vehicle-health-title"><span>VEHICLE HEALTH</span><strong>{vehicle.health}%</strong></div><Progress value={vehicle.health}/><div className="detail-grid vehicle-detail-grid"><div><span>SEVERE IMPACTS</span><strong>{vehicle.impacts}</strong></div><div><span>RISK LEVEL</span><strong>{vehicle.risk}</strong></div><div><span>DISTANCE</span><strong>{vehicle.distance}</strong></div><div><span>EFFICIENCY</span><strong>{vehicle.efficiency}</strong></div></div><div className="action-callout"><Wrench/><div><strong>{vehicle.status}</strong><span>Prioritise suspension, alignment, tyre pressure, and underbody checks.</span></div></div><Button className="detail-primary" onClick={()=>notify(`Inspection scheduled for ${vehicle.id}`)}><Wrench/> Schedule inspection</Button><Button variant="outline" className="detail-secondary" onClick={()=>notify("Driver notification sent")}>Notify driver</Button></div></>}</SheetContent></Sheet>}
